apiVersion: v1
kind: Secret
metadata:
    name: mysqlcreds
type: Opaque
stringData:
    DB_USER: ENC[AES256_GCM,data:TbNxsw==,iv:cs6HusYMDHPLN2mExAHUBI/xgh4XY+tRFc+MXvD1ZQM=,tag:brDhP6z8prapJHdZRe55HQ==,type:str]
    DB_PASSWORD: ENC[AES256_GCM,data:0lSaqBQ=,iv:G+wXz0a+fFnxKrLWIOqubv/ukXE02c+Ko2lI9wttqLA=,tag:TJZz+jVufId0hhGMT1rh9A==,type:str]
sops:
    kms: []
    gcp_kms: []
    azure_kv: []
    hc_vault: []
    age: []
    lastmodified: "2023-10-19T14:51:26Z"
    mac: ENC[AES256_GCM,data:fONEotcqkAovqoL7kKKnWCU1ua0x8hx9fbAzSfIbyDgF+pg0HQevQ2QsKcgmaKJLa5qk9bxQa7NpKdboSMp/b959rBfAW1Th7fzt5sIYaklWwCTet9+aSUsM8Xa4Wjze2ywncsDRaXccn/Y0K9QlorvaIvG6t+ZJ3t6UTQpi51w=,iv:UxMl+4XTsFCVS3WErzHJ24CWT/mKOJGKiy5m4BqLTrg=,tag:Cy+gKChTdyV0Vb0DoCfZXQ==,type:str]
    pgp:
        - created_at: "2023-10-19T14:48:51Z"
          enc: |-
            -----BEGIN PGP MESSAGE-----

            hQEMA1xiQPM+98ylAQgAko6WRpLGuxJkDVbVqdsVJaOTU1JH66kveCXkxPwdLlRv
            qTeTjYClbIbvsTYcFjxiRfdKchKIUYp1YFWT/16p2fhZJF9/X8PSrQh/vEbclLJU
            ZCHxIBxp18tp2NO05TDUCar9gn/g2XF+8tGqOem2jPRBpW+AE9wJe9b71IbhLEkD
            jewuIIfiBsZyT1jg/SO1si+DMF40iu0nU4EBFYowdC/MhEGZHi5CcbuLgMPmRrHJ
            6d7RADV5V83t/oD7Wk4MkYEdDPnpm4cE//EPHQnlNQnyDISvVwfJnFj4Zfk905t5
            VkeclvkoJVmhbvPr0wffJWKlOvv3NuS9NGuKjfoPENJcAZWC95xUpYaizutdXcB6
            5QajMb931jEVy2B0MgZMoGS2PNhT1X81xpHB1mcX1Z80DzpHm+HiNYqGkpdYLy8O
            7oJpMT8JBxT53PhoyYZpvKpc5u4REwyVKTqV6ao=
            =6cLt
            -----END PGP MESSAGE-----
          fp: AE7818BECE7AE92701F994B6143400119DF78364
    encrypted_regex: ^(data|stringData)$
    version: 3.8.1
